### PR TITLE
Use latest dns2 library from Packagist

### PR DESCRIPTION
**Pull request by DarioSwain**
#51 Use latest stable pear/net_dns2 package from packagist instead Pear.

### CODE REVIEW

**Comment by cpliakas** [comment]
@DarioSwain Thanks for the contribution.

Don't worry about the scrutinizer stuff, the settings are a little too restrictive and need to be tweaked. Regarding the code change, I am 100% in favor of using the packagist version of this package. The reason why it is pinned to 1.3.2 is because it is (or was) the same version that is used on the Acquia Cloud platform, and if possible I want to maintain parity.

I do need to check whether this is still the case, but in the meantime are there any specific reasons why we should upgrade to the 1.4 version, e.g. security issues, bug fixes, etc? I do think that keeping current is always the best option, I just want to understand the context so that we don't accidentally introduce instability if we don't have to.

Thanks again for the pull request.
Chris

**Comment by DarioSwain** [comment]
Hi @cpliakas, 
Sorry for long reply.

I think it's a good point to use ```~``` for patch versions, you can see more information here: [semver](http://semver.org/).
At now i don't see v1.3.2 tag for net_dns2 on GitHub, maybe make sense create issue for moving all version tags from Pear to GitHub. I check it later.
But now, i [compare v1.3.2 and v1.4.1](https://github.com/mikepultz/netdns2/compare/8df60379bef9c48a3f26b4d34f7ef27d828331cc...v1.4.1) and seems like it fix some bugs and provide more functionality, include normal autoloading. In you case, you only use Resolver component and i don't see any changes for it.

But I think you are right, you must check this version before merge this PR. From my side i don't see any reasons to use old version of packages, if you check pear, v1.4.1 mark as a stable. Maybe it good point to move all Acquia infrastructure to new version ... it only your choice

**Comment by DarioSwain** [comment]
@cpliakas please check [this issue](https://github.com/mikepultz/netdns2/issues/36). 
I update this PR, at now I use 1.3.2 version of net_dns2 package.
It more useful?

**Comment by cpliakas** [comment]
@DarioSwain, sorry for the long turnaround on this. Thanks for the contribution!

**Pull request merged**
